name: api_login
description: "A new Flutter project."

publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  mask_text_input_formatter: ^2.2.0
  page_transition: ^2.1.0
  cupertino_icons: ^1.0.6
  dio: ^5.0.0
  file_picker: ^8.1.3
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  open_file: ^3.3.2
  syncfusion_flutter_pdfviewer: ^24.1.46
  syncfusion_flutter_core: ^24.1.46 
  fluttertoast: ^8.2.8
  url_launcher: ^6.3.1
  flutter_pdfview: ^1.3.4
  path_provider: ^2.1.5
  shared_preferences: ^2.1.0
  geolocator: ^13.0.1
  flutter_localizations:
    sdk: flutter
  onesignal_flutter: ^5.2.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Ajustado para versão compatível
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/background_login.png
    - assets/images/check.webp
    - assets/images/selo_opac2.png
